src/wfs/endpoint.js
src/wfs/endpoint.spec.js

There are several examples of OGC servers being able to answer on application/json for example while this format not being listed in the capabilities.

WFS / do not throw if asking for an unknown WFS output format

---

src/shared/cache.spec.ts
src/shared/cache.ts
src/shared/encoding.ts
src/wfs/endpoint.ts

This handles a rejection in the `caches.open()` promise and simply disables caching when it happens. It will also print the reason in the console.
Fixes #15

Support for browser cache not being available (i.e. in private mode)

---

src/ogc-api/endpoint.spec.ts
src/ogc-api/endpoint.ts

This pull request introduces the `getCollectionItemsUrl` method in the `OgcApiEndpoint` class. This method is designed to generate a URL for the items of a specified collection, with optional query parameters. 
The parameters include query, outputFormat, maxFeatures, skipGeometry, offset, outputCrs, extent, extentCrs, and properties. The method returns a promise that resolves to the URL as a string or rejects if an error occurs.
In addition to the method, this PR also includes unit tests to ensure the correct functionality of the `getCollectionItemsUrl` method.
This addition enhances the functionality of the `OgcApiEndpoint` class, providing more flexibility and options for users when working with collection items.

Add getCollectionItemsUrl Method for OGC API

---

src/ogc-api/endpoint.spec.ts
src/ogc-api/endpoint.ts
src/ogc-api/info.ts
src/ogc-api/model.ts

* More robust lookup of collection document: calling `getCollectionInfo` on the sample-data-2 fixtures was failing without this logic (no rel=self link is present on collections)
* Base documents of the endpoint (root doc, collections) are now queried lazily instead of eagerly at the endpoint creation; this will avoid unhandled promise rejection and offer clearer errors
* A new `bulkDownloadLinks` property was added to collections: these are links of type "enclosure" which do not offer pagination, filter etc. but only a bulk download; the property is a map between the mime type and the url

OGC API: misc improvements

---

fixtures/ogc-api/sample-data-2/collections/aires-covoiturage.json
fixtures/ogc-api/sample-data/collections/airports.json
src/ogc-api/endpoint.spec.ts
src/ogc-api/endpoint.ts
src/ogc-api/link-utils.ts
src/ogc-api/model.ts
src/shared/mime-type.spec.ts
src/shared/mime-type.ts
src/wfs/endpoint.ts

This PR improves the way getCollectionItmsUrl by choosing one of the available items url according to the desired mime-type, instead of generating it dynamically.
Also adds an `asJson` option to simply get the first items url that matches JSON-FG or GeoJSON.

OGC API: use actual mimetype to generate an items url

---

README.md
app/src/Docs.vue

- to run the example app you need to run `npm install` in the main package as well
- remove unnecessary `await` in the example code

Minor improvements to the application docs

---

.github/workflows/publish.yml
README.md
package-lock.json
package.json

The workflow will only run on the `main` branch.
The version published will be `<npm version>.<git commit>`, e.g.: `1.1.1-dev.0a4c598`
This PR also bumps the version to 1.1.1-dev

Auto-publish @dev version on NPM

---

src/wfs/endpoint.spec.ts
src/wfs/endpoint.ts
src/wfs/url.spec.ts
src/wfs/url.ts

This PR includes the following updates:
- Introduces the support for `startIndex` in the `getFeatureUrl` and `generateGetFeatureUrl` functions
- Adds a `supportsStartIndex` method in the `WfsEndpoint` class.

[WFS] Add startIndex Support in URL generation and supportsStartIndex Method

---

src/ogc-api/endpoint.spec.ts
src/ogc-api/link-utils.ts
src/shared/http-utils.spec.ts
src/shared/http-utils.ts

This PR makes sure that concurrent identical requests made in an OGC API context will be merged, thus drastically diminishing the amount of requests when exploring the contents of an OGC API endpoint.

Use sharedFetch in OGC API endpoint queries

---

src/ogc-api/endpoint.spec.ts
src/ogc-api/link-utils.ts
src/shared/http-utils.spec.ts
test-setup.ts

When sharing fetch calls, the resulting data stream can only be consumed once. Now it is cloned before being consumed.

OGC API: Avoid "stream already consumed" errors on shared fetch calls

---

app/src/components/wms/WmsEndpoint.vue
app/src/components/wms/WmsLayerInfo.vue
src/index.ts
src/wms/capabilities.ts
src/wms/endpoint.spec.ts
src/wms/endpoint.ts
src/wms/model.ts
src/wms/url.spec.ts
src/wms/url.ts

This fixes #47 by providing a utility to generate a GetMap url in a safe way (including the VERSION param). This function is not complete yet, and do not handle parameters such as TILED, pixel ratio etc.

Add utility in WMS endpoint to build a GetMap url

---

fixtures/ogc-api/sample-data/collections/dutch-metadata/items.json
fixtures/ogc-api/sample-data/collections/dutch-metadata/items/35149dfb-31d3-431c-a8bc-12a4034dac48.json
fixtures/ogc-api/sample-data/collections/dutch-metadata/queryables.json
src/ogc-api/endpoint.spec.ts
src/ogc-api/model.ts

It seems that the OGC API Records model is not uptodate.
Reference: https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordCommonProperties.yaml
- `languages`
- `externalIds`
- `created`
- `updated`
etc...

ogc-records: update schema

---

app/src/components/wfs/WfsFeatureTypeInfo.vue
app/src/components/wms/WmsLayerInfo.vue
fixtures/wms/capabilities-brgm-1-1-1.xml
src/wfs/capabilities.spec.ts
src/wfs/capabilities.ts
src/wfs/endpoint.spec.ts
src/wfs/endpoint.ts
src/wfs/featuretypeinfo.ts
src/wfs/model.ts
src/wms/capabilities.spec.ts
src/wms/capabilities.ts
src/wms/endpoint.spec.ts
src/wms/model.ts

This PR adds keywords to the WMS and WFS layers/featuretypes output, in the same way that keywords are added to the top level capability documents.
One of the test fixtures (fixtures/wms/capabilities-brgm-1-1-1.xml) had to be modified to make them consistent between versions (keywords didn't appear in one version that did in another). I felt changing the fixture was safer but it could be changed to instead change the test to handle the differences.

Add keywords to WMS and WFS

---

fixtures/ogc-api/sample-data/collections/airports/styles/Tritanopia/metadata.json
fixtures/ogc-api/sample-data/styles/Deuteranopia/metadata.json
fixtures/ogc-api/sample-data/styles/Light/metadata.json
fixtures/ogc-api/sample-data/styles/Night/metadata.json
fixtures/ogc-api/sample-data/styles/Outdoor/metadata.json
fixtures/ogc-api/sample-data/styles/OutdoorHillshade/metadata.json
fixtures/ogc-api/sample-data/styles/Road/metadata.json
fixtures/ogc-api/sample-data/styles/Tritanopia/metadata.json
src/ogc-api/endpoint.spec.ts
src/ogc-api/endpoint.ts
src/ogc-api/info.ts
src/ogc-api/link-utils.ts
src/ogc-api/model.ts

This attempts to add basic support for styles. For now just retrieving styles is supported.
Examples:
Get a list of available style identifiers:
```js
const endpoint = new OgcApiEndpoint('https://demo.ldproxy.net/zoomstack');
await endpoint.listAllStyles;
```
Get a list of styles (includes the supported formats, which you need for `getStylesheetUrl`):
```js
await endpoint.allStyles;
```
Get style metadata:
```js
await endpoint.getStyleMetadata('Deuteranopia');
```
Get stylesheet URL from metadata (or style document):
```js
await endpoint.getStylesheetUrl('Deuteranopia', 'application/vnd.esri.lyr');
```
Some questions / notes:
- not sure if the extra type `OgcApiStyleDocument` is needed - you could also use `OgcApiDocument` here if you add a `styles` subproperty. This would remove the need …

Support for OGC API Styles

---

package-lock.json
package.json
vite.node-config.js

This makes the node bundle go from 280k to 240k; node-fetch is now a runtime dependency.
Should also fix issues with missing dependencies when using the node bundle (e.g. `data-buffer-to-uri`)

Node bundle: make `node-fetch` an external dependency

---

package.json

This would cause errors when trying to use the lib in a TS project.

NPM package typings are actually in the src folder as TS files

---

package.json
vite.node-config.js
vite.worker-config.js

Reverts #61 as it is not recommended to publish TS files in a lib without d.ts files.
The build process now does not clear the dist folder between builds, which used to not make sense.

Keep d.ts files in package

---

src/shared/models.ts
src/wms/capabilities.spec.ts
src/wms/capabilities.ts
src/wms/endpoint.spec.ts

This PR adds `infoFormats` as a property to the capabilities model. `infoFormats` are derived from the WMS GetFeatureInfo formats list and provide a list of formats (MIME types) that can be used in GetFeatureInfo requests. 
This has been added to the `GenericEndpointInfo` class, however, this list is only retrieved in WMS scenarios, so this may not be the right place. Happy to take suggestions on a more appropriate place for this.

Add info formats to WMS capabilities

---

src/shared/models.ts
src/wms/capabilities.spec.ts
src/wms/capabilities.ts
src/wms/endpoint.spec.ts

This PR builds on #66 and adds additional support for retrieving the list of available Exception formats from WMS capabilities.
Although this list is usually static - varying depending only on the WMS version being used - according to the standard only the XML format is required and the image exception formats may therefore not be available on a given WMS endpoint.
Note that I have deliberately set the type definition for `exceptionFormats` to `MimeType[] | string[]` because the WMS 1.3.0 spec does not use MIME-like syntax for the format strings.

Add support for retrieving exception formats from WMS capabilities

---

src/index.ts
src/shared/models.ts
src/shared/ows.spec.ts
src/shared/ows.ts
src/wfs/capabilities.spec.ts
src/wfs/capabilities.ts
src/wfs/endpoint.spec.ts
src/wms/capabilities.spec.ts
src/wms/capabilities.ts
src/wms/endpoint.spec.ts
src/wmts/capabilities.spec.ts
src/wmts/capabilities.ts
src/wmts/endpoint.spec.ts

It is often required as part of an application to show the metadata regarding the service provider which is included in capabilities documents (WFS 1.1+, WMS 1.1+, WMTS). This commit exposes this information in a common format as part of the GenericEndpointInfo structure.
Note that this information is already included in the OgcApiCollectionInfo structure.

Expose provider information from capabilities

---

fixtures/wfs/exception-report-1-1-0.xml
fixtures/wfs/exception-report-2-0-0.xml
fixtures/wfs/exception-report-wms.xml
fixtures/wfs/service-exception-report-1-0-0.xml
fixtures/wms/service-exception-report-1-1-0.xml
fixtures/wms/service-exception-report-1-1-1.xml
fixtures/wms/service-exception-report-1-3-0.xml
fixtures/wms/service-exception-report-wfs.xml
src/index.ts
src/shared/service-exception-error.spec.ts
src/shared/service-exception-error.ts
src/wfs/endpoint.spec.ts
src/wms/endpoint.spec.ts
src/worker/worker.ts

If the WMS or WFS service responds to a GetCapabilities request with a ServiceException report then this will be recognised and the promise rejected with a ServiceExceptionError.
This could also be extended for WFS DescribeFeatureType etc., but initially we concentrate just on GetCapabilities requests.

Add recognition of service exception reports

---

fixtures/wfs/describefeaturetype-pigma-1-1-0-xsd.xml
src/wfs/featuretypeinfo.ts

Hopefully this will be enough to cover all server implementations. An alternative is to read which prefix is used for the XSD namespace and check for that, but for now we can try like that.
Fixes #75

Allow using xs: prefix for feature type attributes

---

src/shared/models.ts
src/wfs/capabilities.spec.ts
src/wfs/capabilities.ts
src/wfs/endpoint.spec.ts
src/wfs/endpoint.ts
src/wms/capabilities.spec.ts
src/wms/capabilities.ts
src/wms/endpoint.spec.ts
src/wms/endpoint.ts
src/worker/index.ts
src/worker/worker.ts

OWS Capability documents include definitions of the URLs to be used for all operations. As a general rule these are (i) all the same and (ii) the same as the URL from which the capabilities document was retrieved. This is however not necessarily the case, e.g. where request forwarding has occured. Formally, these self-reported URLs should be used for all operations.
This PR therefore exposes the self-reported operation URLs in the API and also uses these as the base for generated request URLs.
Notes:
1. some changes in some existing tests were necessary as "fake" URLs are used for mock requests, which are replaced by the self-reported URLs once the capabilities have been replaced.
2. Tests for the capabilities URL before the loading has completed (which will return a value based on using …

Use self-reported operation URLs from capability documents

---

src/wmts/capabilities.spec.ts
src/wmts/capabilities.ts

ACCES.BIOMETHANE layer from this service : https://data.geopf.fr/wmts?SERVICE=WMTS&VERSION=1.0.0 shows these informations:
```
Identifier
PM_6_16
Crs
EPSG:2154
```
But the CRS should be EPSG:3857 instead of EPSG:2154.
This PR aims to correct this behaviour. Let me know if I need to make any changes to the code.

Fix wrong crs for wmts layer

---

src/ogc-api/endpoint.spec.ts
src/ogc-api/link-utils.ts

This PR fixes the manipulation of a URL. Instead of handling it as a string it will be handled as URL-Object.
This was mentioned here: https://github.com/camptocamp/ogc-client/issues/85

Fix URL manipulation in link-utils

---

fixtures/ogc-api/root-path.json
fixtures/ogc-api/sample-data-root.json
fixtures/ogc-api/sample-data-root/collections.json
fixtures/ogc-api/sample-data-root/collections/airports.json
fixtures/ogc-api/sample-data-root/conformance.json
src/ogc-api/endpoint.spec.ts
src/ogc-api/link-utils.ts
src/shared/url-utils.spec.ts
src/shared/url-utils.ts

This is required for this service to be parsed:
https://ogcapi.bgs.ac.uk/collections
https://ogcapi.bgs.ac.uk/collections/scanned-maps-1m
https://ogcapi.bgs.ac.uk/collections/scanned-maps-1m/items

OGC API / Handle the case when the root document is situated at the `/` path

---

src/ogc-api/endpoint.spec.ts
src/ogc-api/endpoint.ts
src/shared/models.ts

Added optional `datetime` filtering parameter to `getCollections` endpoint function in response to [Issue-90](https://github.com/camptocamp/ogc-client/issues/90)

datetime-parameter-filtering

---

src/ogc-api/endpoint.ts
src/ogc-api/link-utils.ts
src/shared/url-utils.spec.ts
src/shared/url-utils.ts

Fixes https://github.com/camptocamp/ogc-client/issues/111
The issue was caused by a flawed logic when creating the collection document URL.
This PR also includes better error handling in case some links which are expected to be there were not present. This should give better feedback in cases where the endpoint has quirks and specificities that are not expected by the library

Fix error when reading an OGC API endpoint provided by QGIS

---

app/src/Docs.vue
jest.node.config.cjs
package-lock.json
package.json
src-node/index.ts
src-node/polyfills.ts
src/ogc-api/endpoint.ts
src/ogc-api/link-utils.ts
src/shared/url-utils.spec.ts
src/shared/url-utils.ts
src/tms/link-utils.ts
test-setup.node.ts
test-setup.ts
vite.node-config.js

This PR attempts to change:
- Explicitly states supported node version (`20+`) in `package.json` and `docs`
- Drops 3rd party polyfills and use runtime bultins, namely `fetch`, `Blob`  and `async/await`
- Removes monkey patching on globals, namely `CustomEvent` and `location`
- Adds `exports` in `package.json` 
Fixes: #121

refactor: move to node 20
